# Generated by Django 5.1.4 on 2025-01-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pers_acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('fract', models.CharField(max_length=20)),
                ('flat', models.IntegerField(max_length=50)),
                ('big_square', models.IntegerField(max_length=10)),
                ('square', models.IntegerField(max_length=10)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_location', to='pers_acc.personal_account')),
            ],
            options={
                'ordering': ['-update'],
                'indexes': [models.Index(fields=['-update'], name='location_lo_update_3e513c_idx')],
            },
        ),
    ]
