# Generated by Django 5.1.4 on 2025-01-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='acc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
