# Generated by Django 5.1.4 on 2025-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_acc', '0002_alter_personal_account_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_account',
            name='acc',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
